global:
  scrape_interval: 5s  # Scrape metrics every 5 seconds

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:8080"]  # Use host.docker.internal for the host machine


