version: '3.8'

services:
  self-driving_original:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self-driving_original
    environment:
      - APP_FILE=app_original
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  self-driving_pca2000:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self-driving_pca2000
    environment:
      - APP_FILE=app_pca2000
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  self-driving_pca500:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self-driving_pca500
    environment:
      - APP_FILE=app_pca500
    ports:
      - "8002:8000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    privileged: true 
    

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana 
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-data:
