{
 "title": "Image Classification - Mobilenet/CIFAR-10",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mobilenet_original\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name=\"mobilenet_original\"}) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"mobilenet_original\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 500 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mobilenet_pca500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Top 500 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"mobilenet_pca500\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"mobilenet_pca500\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 200 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mobilenet_pca200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Top 200 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"mobilenet_pca200\"}/ 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"mobilenet_pca200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}