{
 "title": "Self-Driving Decision Making",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Utilization - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"self-driving_original\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"self-driving_original\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O - Full Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"self-driving_original\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 2000 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"self-driving_pca2000\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Top 2000 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"self-driving_pca2000\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O - Top 2000 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"self-driving_pca2000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 500 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"self-driving_pca500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage - Top 500 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"self-driving_pca500\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O - Top 500 Features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"self-driving_pca500\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}